[package]
name = "bullet"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
tui-textarea = "0.7.0"
ratatui = "0.29.0"
serde = {version = "1.0.219", features = ["derive"]}
open = "5.3.2"
serde_json = "1.0.140"
