[package]
name = "bullet"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
tui-textarea = "0.7.0"
ratatui = "0.29.0"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.8.20"
