# [[dirs]]

# [[apps]]

[[urls]]
path = "https://mkrs-beta.vercel.app"
seq = ["mkrs", "ьлкы", "мкрс", "vrhc"]
description = "MKRS - Small chinese-russian dictionary"

[[urls]]
path = "https://bkrs.info"
seq = ["bkrs", "илкы", "бкрс", ",rhc"]
description = "BKRS - Big chinese-russian dictionary"

[[urls]]
path = "https://youtube.com"
seq = ["y", "н"]
description = "Youtube"

[[urls]]
path = "https://twitch.tv"
seq = ["tw.", "ецю"]
description = "Twitch"

[[urls]]
path = "https://twitch.tv/directory/all/tags/中文"
seq = ["twc", "ецс"]
description = "Twitch / Chinese"